### ISSUE TITLE
Code view does not work.

### ISSUE THREAD

**Issue by davidrichied** [froala/wordpress-froala-wysiwyg#6]
Code view does not work because the codemirror libraries (and code view css) are not included in the project. I think these should be included by default to make code view work, kind of like how the WordPress editor includes the normal view and text view. 

I forked the repo, added the libraries, and made a pull request.

**Comment by stefanneculai** [comment]
Thanks! We'll review it shortly.

**Comment by mattbucci** [comment]
@stefanneculai it looks like this PR is not yet merged https://github.com/froala/wordpress-froala-wysiwyg/pull/5 

any updates?
